"""Export Small Practice Security Kit–compatible AI review artifacts.

Produces:
  - ai-workflow-review.md  (kit table shape: allowed / restricted / prohibited)
  - handoff-actions.csv    (owner/MSP handoff rows for AI workflows)
  - kit-import-manifest.json

Artifacts are PHI-avoidant: decisions, rule IDs, evidence *references* only.
"""

from __future__ import annotations

import csv
import io
import json
from pathlib import Path
from typing import Any


DECISION_TO_KIT = {
    "approve": "allowed",
    "approve_with_conditions": "restricted",
    "restrict": "restricted",
    "block": "prohibited",
}

DECISION_TO_LIFECYCLE = {
    "approve": "Closed",
    "approve_with_conditions": "Requested",
    "restrict": "Requested",
    "block": "Blocked",
}

DECISION_TO_CLOSEOUT = {
    "approve": "Closed",
    "approve_with_conditions": "Needs evidence",
    "restrict": "Needs evidence",
    "block": "Blocked",
}

DECISION_TO_TIMEFRAME = {
    "approve": "90_days",
    "approve_with_conditions": "30_days",
    "restrict": "30_days",
    "block": "30_days",
}


def write_kit_bridge(report: dict[str, Any], out_dir: Path) -> dict[str, Path]:
    """Write kit-importable AI workflow artifacts into out_dir."""
    out_dir.mkdir(parents=True, exist_ok=True)
    paths = {
        "ai_workflow_review": out_dir / "ai-workflow-review.md",
        "handoff_actions": out_dir / "handoff-actions.csv",
        "manifest": out_dir / "kit-import-manifest.json",
    }
    paths["ai_workflow_review"].write_text(render_ai_workflow_review(report), encoding="utf-8")
    paths["handoff_actions"].write_text(render_handoff_csv(report), encoding="utf-8")
    paths["manifest"].write_text(
        json.dumps(build_manifest(report), indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    return paths


def render_ai_workflow_review(report: dict[str, Any]) -> str:
    metadata = report.get("metadata", {})
    summary = report.get("summary", {})
    lines = [
        "# AI Workflow Review",
        "",
        f"_Generated by HealthAI Audit for {metadata.get('practice', 'Unspecified practice')}. "
        f"Portfolio decision: **{summary.get('portfolio_decision', 'n/a')}**. "
        "Triage support only — not legal or HIPAA certification advice._",
        "",
        "| Workflow | Use | Data Used | Vendor | Decision | Lifecycle | Closeout | Trace | Evidence Needed |",
        "| --- | --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for item in report.get("assessments", []):
        kit_decision = DECISION_TO_KIT.get(str(item.get("decision")), "restricted")
        data_used = _data_used(item)
        evidence_needed = _evidence_needed(item)
        rules = ", ".join(item.get("rule_ids") or []) or "none"
        lines.append(
            "| "
            + " | ".join(
                [
                    _cell(item.get("name")),
                    _cell(item.get("workflow")),
                    _cell(data_used),
                    _cell(item.get("vendor")),
                    _cell(kit_decision),
                    _cell(DECISION_TO_LIFECYCLE.get(str(item.get("decision")), "Requested")),
                    _cell(DECISION_TO_CLOSEOUT.get(str(item.get("decision")), "Needs evidence")),
                    _cell(f"rules {rules}; vendors {item.get('vendor', '')}"),
                    _cell(evidence_needed),
                ]
            )
            + " |"
        )

    lines.extend(
        [
            "",
            "## Rules of Thumb",
            "",
            "- **Allowed**: inventory gaps closed; PHI tools have non-expired evidence refs; no block rules.",
            "- **Restricted**: usable only under guardrails or with tracked conditions / missing evidence.",
            "- **Prohibited**: critical governance rules open (BAA, training, autonomous MCP, etc.).",
            "",
            "## Rule IDs",
            "",
        ]
    )
    for item in report.get("assessments", []):
        if not item.get("rule_ids"):
            continue
        lines.append(f"- **{item.get('name')}**: {', '.join(item.get('rule_ids') or [])}")
    if not any(item.get("rule_ids") for item in report.get("assessments", [])):
        lines.append("- No open rule IDs.")

    lines.extend(
        [
            "",
            "## Evidence references (paths only)",
            "",
        ]
    )
    any_refs = False
    for item in report.get("assessments", []):
        for ref in item.get("evidence_refs") or []:
            any_refs = True
            lines.append(
                f"- `{ref.get('id')}` · {item.get('name')} · kind={ref.get('kind')} · "
                f"path=`{ref.get('path')}` · reviewed={ref.get('reviewed_on') or 'n/a'}"
            )
    if not any_refs:
        lines.append("- No evidence refs recorded in inventory.")

    lines.extend(
        [
            "",
            "## Import note",
            "",
            "Copy this file into a Small Practice Security Kit demo/packet slot as "
            "`ai-workflow-review.md`, or merge rows into your practice AI workflow table. "
            "Do not paste PHI, credentials, or raw contracts into the kit.",
            "",
        ]
    )
    return "\n".join(lines)


def render_handoff_csv(report: dict[str, Any]) -> str:
    """Kit-shaped handoff rows focused on AI workflow actions."""
    fieldnames = [
        "action_id",
        "audience",
        "recipient",
        "stage_id",
        "priority",
        "owner",
        "action",
        "title",
        "plain_english_summary",
        "why_it_matters",
        "risk_area",
        "affected_workflows",
        "owner_lane",
        "timeframe",
        "acceptable_evidence",
        "unsafe_inputs",
        "next_action",
        "evidence_ref",
        "artifact_ref",
        "rule_ids",
        "kit_decision",
        "healthai_decision",
    ]
    buffer = io.StringIO()
    writer = csv.DictWriter(buffer, fieldnames=fieldnames, extrasaction="ignore")
    writer.writeheader()

    for index, item in enumerate(report.get("assessments", []), start=1):
        decision = str(item.get("decision", "restrict"))
        kit_decision = DECISION_TO_KIT.get(decision, "restricted")
        priority = "high" if decision in {"block", "restrict"} else "medium"
        if decision == "approve":
            priority = "low"
        action_id = f"HA-AI-{index:03d}"
        rules = ", ".join(item.get("rule_ids") or [])
        evidence_ids = ";".join(ref.get("id", "") for ref in (item.get("evidence_refs") or []) if ref.get("id"))
        reason = (item.get("decision_reasons") or ["Review AI workflow boundaries."])[0]
        owner = "Office Manager" if decision != "block" else "Practice owner / MSP"
        action = _action_text(item, kit_decision)
        writer.writerow(
            {
                "action_id": action_id,
                "audience": "owner_msp",
                "recipient": "Owner/MSP",
                "stage_id": "ai_phi_review",
                "priority": priority,
                "owner": owner,
                "action": action,
                "title": f"AI workflow: {item.get('name', 'tool')}",
                "plain_english_summary": reason,
                "why_it_matters": (
                    "AI workflows need explicit data boundaries so staff do not enter patient, "
                    "billing, clinical, credential, or raw evidence details into the wrong tool."
                ),
                "risk_area": "AI workflow review",
                "affected_workflows": str(item.get("workflow", "")),
                "owner_lane": "office_manager",
                "timeframe": DECISION_TO_TIMEFRAME.get(decision, "30_days"),
                "acceptable_evidence": (
                    "evidence reference ID; BAA status; reviewed_on date; MCP allowlist path; "
                    "human-approval setting; no PHI"
                ),
                "unsafe_inputs": (
                    "patient names; patient records; credentials; private portal links; "
                    "raw logs; clinical notes; claim narratives"
                ),
                "next_action": action,
                "evidence_ref": evidence_ids,
                "artifact_ref": "ai-workflow-review.md",
                "rule_ids": rules,
                "kit_decision": kit_decision,
                "healthai_decision": decision,
            }
        )

    # Also emit one row per blocking action-queue item that is not just a risk band.
    seen_actions = {row for row in buffer.getvalue().splitlines()}
    _ = seen_actions  # silence; rows already unique by tool
    return buffer.getvalue()


def build_manifest(report: dict[str, Any]) -> dict[str, Any]:
    summary = report.get("summary", {})
    metadata = report.get("metadata", {})
    return {
        "schema": "velari.kit_bridge.v1",
        "source": "health-ai-governance-auditor",
        "method": metadata.get("method"),
        "practice": metadata.get("practice"),
        "generated_at_utc": metadata.get("generated_at_utc"),
        "portfolio_decision": summary.get("portfolio_decision"),
        "tool_count": summary.get("tool_count"),
        "decision_counts": summary.get("decision_counts"),
        "blocking_rule_ids": summary.get("blocking_rule_ids"),
        "artifacts": [
            "ai-workflow-review.md",
            "handoff-actions.csv",
            "kit-import-manifest.json",
        ],
        "import_guidance": (
            "Copy ai-workflow-review.md and merge handoff-actions.csv into Small Practice "
            "Security Kit packet outputs. Human-preview before import; no PHI."
        ),
        "disclaimer": metadata.get("disclaimer"),
    }


def _data_used(item: dict[str, Any]) -> str:
    data_types = item.get("data_types")
    if isinstance(data_types, list) and data_types:
        return ", ".join(str(x) for x in data_types)
    status = item.get("evidence_status") or {}
    if status.get("touches_phi"):
        return "PHI or PHI-adjacent (per inventory flags)"
    return "see inventory data_types"


def _evidence_needed(item: dict[str, Any]) -> str:
    refs = item.get("evidence_refs") or []
    gaps = (item.get("evidence_status") or {}).get("gaps") or []
    if item.get("decision") == "approve" and refs:
        return "maintain evidence refs: " + "; ".join(r.get("id", r.get("path", "")) for r in refs[:3])
    if gaps:
        return "; ".join(str(g) for g in gaps[:2])
    if item.get("decision") == "block":
        return "close blocking rules before evidence collection expands use"
    return "BAA/policy evidence ref; human approval; logging; no-PHI staff guidance"


def _action_text(item: dict[str, Any], kit_decision: str) -> str:
    name = item.get("name", "AI tool")
    if kit_decision == "prohibited":
        return f"Pause {name} until blocking HealthAI rules are closed and evidence refs exist."
    if kit_decision == "restricted":
        return f"Keep {name} restricted; collect evidence refs and close open rule IDs before expansion."
    return f"Maintain allowed use of {name}; re-review evidence refs on next cadence."


def _cell(value: Any) -> str:
    return str(value if value is not None else "").replace("\n", " ").replace("|", "\\|").strip()
